/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ADMIN_LOGIN.java
 *
 * Created on Apr 21, 2012, 4:38:56 PM
 */

package project;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Uday
 */
public class ADMIN_LOGIN extends javax.swing.JFrame {

    /** Creates new form ADMIN_LOGIN */
    public ADMIN_LOGIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ONLINE SHOPPING");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24));
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("ADMIN LOGIN");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("PASSWORD :");

        B2.setBackground(new java.awt.Color(102, 102, 255));
        B2.setFont(new java.awt.Font("Century", 1, 14));
        B2.setText("OK");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(255, 153, 153));
        B4.setFont(new java.awt.Font("Century", 1, 14));
        B4.setText("CLOSE");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        p1.setFont(new java.awt.Font("Arial Black", 1, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(B2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(B4)))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2)
                    .addComponent(B4))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 330, 130));

        jLabel3.setForeground(new java.awt.Color(236, 233, 216));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        String a=new String(p1.getPassword());
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost/ONLINE_SHOP";
            Connection conn = DriverManager.getConnection(database, "root", "");
            Statement stmt = conn.createStatement();
            String sql="Select * from LOGIN where PWD='"+a +"'";
            ResultSet rs=stmt.executeQuery(sql);
            int c=0;
            while(rs.next()) {
                c++;
            }
            if(c>0) {
                JOptionPane.showMessageDialog(null,"ACCESS GRANTED !!!!!!");
                stmt.close();
                conn.close();
                this.setVisible(false);
                ADMIN_PAGE p=new ADMIN_PAGE();
                p.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null,"ACCESS DENIED !!!!!!!!!!!!!");
                stmt.close();
                conn.close();
                this.setVisible(false);
                Introduction p=new Introduction();
                p.setVisible(true);
            }
        } catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}
}//GEN-LAST:event_B2ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       Introduction OB=new Introduction();
        OB.setVisible(true);
}//GEN-LAST:event_B4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2;
    private javax.swing.JButton B4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField p1;
    // End of variables declaration//GEN-END:variables

}
