/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDITITEM.java
 *
 * Created on Apr 21, 2012, 4:51:02 PM
 */

package project;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Uday
 */
public class EDITITEM extends javax.swing.JFrame {
 public void fill()
{
       cb1.removeAllItems();
       cb1.setEnabled(true);
       b1.setEnabled(true);
    try
        {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost/ONLINE_SHOP";
            Connection conn = DriverManager.getConnection(database, "root", "");
            Statement stmt = conn.createStatement();
            String s = "select IT_NAME from ITEMS";
            ResultSet rs=stmt.executeQuery(s);
            int c=0;
            while (rs.next())
            {
                String a=rs.getString(1);
                cb1.addItem(a);
                c++;
            }
            if(c==0)
            {
                JOptionPane.showMessageDialog(null," NO ITEMS IN STOCK !!!!");
                rs.close();
                stmt.close();
                conn.close();
                this.dispose();
                ADMIN_PAGE OB=new ADMIN_PAGE();
                OB.setVisible(true);
            }
            
            QTY.setText("");
            RT.setText("");
            B1.setEnabled(false);
            B2.setEnabled(false);
            B3.setEnabled(false);            
            B6.setEnabled(false);            
            QTY.setEnabled(false);
            RT.setEnabled(false);
            rs.close();
            stmt.close();
            conn.close();
         }
         catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}
}
    /** Creates new form EDITITEM */
    public EDITITEM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        QTY = new javax.swing.JTextField();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RT = new javax.swing.JTextField();
        FC = new javax.swing.JFileChooser();
        B6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        b1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ONLINE SHOPPING");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WO(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MODIFY ITEM");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        QTY.setFont(new java.awt.Font("Bookman Old Style", 1, 14));

        B1.setBackground(new java.awt.Color(255, 153, 153));
        B1.setFont(new java.awt.Font("Century", 1, 14));
        B1.setText("EDIT");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(102, 102, 255));
        B2.setFont(new java.awt.Font("Century", 1, 14));
        B2.setText("SAVE");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(102, 102, 255));
        B3.setFont(new java.awt.Font("Century", 1, 14));
        B3.setText("CANCEL");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(255, 153, 153));
        B4.setFont(new java.awt.Font("Century", 1, 14));
        B4.setText("CLOSE");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quantity :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Rate :");

        RT.setFont(new java.awt.Font("Bookman Old Style", 1, 14));

        B6.setBackground(new java.awt.Color(102, 102, 255));
        B6.setFont(new java.awt.Font("Century", 1, 14));
        B6.setText("DELETE");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(QTY, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(B6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(B3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(B4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(QTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6)
                    .addComponent(B1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(B2)
                    .addComponent(B3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FC, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B4)
                .addGap(160, 160, 160))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 430, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Select Item :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, -1));

        b1.setFont(new java.awt.Font("Bookman Old Style", 1, 14));
        b1.setText("GO...");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel6.setForeground(new java.awt.Color(236, 233, 216));
        jLabel6.setText("jLabel3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        try {
            QTY.setEnabled(true);
            RT.setEnabled(true);
            B1.setEnabled(false);
            B2.setEnabled(true);
            B4.setEnabled(false);
            B3.setEnabled(true);          
            B6.setEnabled(false);            
        } catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}
}//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        int q =Integer.parseInt(QTY.getText());
        int r =Integer.parseInt(RT.getText());        
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost/ONLINE_SHOP";
            Connection conn = DriverManager.getConnection(database, "root", "");
            Statement stmt = conn.createStatement();
           
                String sql = "update items set  qty=" + q +" where it_name='"+ cb1.getSelectedItem().toString()+"'" ;
                stmt.executeUpdate(sql);
                sql = "update items set rate=" + r +" where it_name='"+ cb1.getSelectedItem().toString()+"'" ;
                stmt.executeUpdate(sql);               
                JOptionPane.showMessageDialog(null,"Item Information Updated !");
                B3.doClick();
                stmt.close();
                conn.close();
        } catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}
}//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        QTY.setText("");        
        RT.setText("");  
        RT.setEnabled(false);
        QTY.setEnabled(false);
        B1.setEnabled(true);
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(true);
}//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ADMIN_PAGE OB=new ADMIN_PAGE();
        OB.setVisible(true);
}//GEN-LAST:event_B4ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        String in=cb1.getSelectedItem().toString();
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost/ONLINE_SHOP";
            Connection conn = DriverManager.getConnection(database, "root", "");
            Statement stmt = conn.createStatement();
            String sql = "delete from items where it_name='" + in +"'" ;
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Information successfully DELETED !!!!!!!");
            stmt.close();
            conn.close();
            fill();
            B3.doClick();
        } catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}
}//GEN-LAST:event_B6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String in=cb1.getSelectedItem().toString();
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost/ONLINE_SHOP";
            Connection conn = DriverManager.getConnection(database, "root", "");
            Statement stmt = conn.createStatement();
            String sql="select * from items WHERE it_nAME='"+ in +"'" ;
            ResultSet rs=stmt.executeQuery(sql);
            if(rs.next()) {                
                QTY.setText(rs.getString(2).toString());
                RT.setText(rs.getString(3).toString());
                B1.setEnabled(true);
                B6.setEnabled(true);
            } 
            else
            {
                QTY.setText("");            
                RT.setText("");              
                B1.setEnabled(false);
                B6.setEnabled(false);                
            }
            stmt.close();
            conn.close();
        } catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}
}//GEN-LAST:event_b1ActionPerformed

    private void WO(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WO
        // TODO add your handling code here:
        fill();
    }//GEN-LAST:event_WO

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDITITEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B6;
    private javax.swing.JFileChooser FC;
    private javax.swing.JTextField QTY;
    private javax.swing.JTextField RT;
    private javax.swing.JButton b1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
