/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VIEW_ITEM.java
 *
 * Created on Apr 21, 2012, 4:51:40 PM
 */

package project;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Uday
 */
public class VIEW_ITEM extends javax.swing.JFrame {

    /** Creates new form VIEW_ITEM */
    public VIEW_ITEM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ONLINE SHOPPING");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WO(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setAutoscrolls(true);

        tb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM NAME", "QUANTITY", "RATE."
            }
        ));
        tb1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 480, 280));

        jButton3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24));
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEMS DETAIL");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 240, -1));

        jLabel3.setForeground(new java.awt.Color(236, 233, 216));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        jLabel4.setForeground(new java.awt.Color(236, 233, 216));
        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ADMIN_PAGE OB=new ADMIN_PAGE();
        OB.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void WO(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WO
        // TODO add your handling code here:
          DefaultTableModel tm = (DefaultTableModel) tb1.getModel();
          try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost/ONLINE_SHOP";
            Connection conn = DriverManager.getConnection(database, "root", "");
            Statement stmt = conn.createStatement();
            String sql = "select * from ITEMS ORDER BY IT_NAME ASC";
            ResultSet r=stmt.executeQuery(sql);
            Object[] newrow = new Object[3];
            while(r.next()) {
                newrow[0]=r.getString(1);
                newrow[1]=r.getString(2);
                newrow[2]=r.getString(3);
                tm.addRow(newrow);
            }
            stmt.close();
            conn.close();
        } catch (Exception e) { JOptionPane.showMessageDialog(null,e.getMessage());}

    }//GEN-LAST:event_WO

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEW_ITEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
